---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
---


# Libraries
```{r warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(Seurat)
library(ggplot2)
library(bspec)
library(sctransform)
library(cowplot)
library(gridExtra)
library(dplyr)
library(patchwork)
library(sctransform)
library(glmGamPoi)
```


# Generate graph (files' prefix: "")
creates Seurat object:   pbmc3k_QA
creates SNN Graph:       pbmc3k_QA_snn
## subsetting
```{r}
# ------- use previously created Seurat object -------
# pbmc3k <- readRDS(file = "data/pbmc_data/pbmc3k/pbmc3k_init.rds")

# ----- Load new PBMC dataset -----
pbmc.data <- Read10X(data.dir = "../../data/pbmc_data/pbmc3k/filtered_gene_bc_matrices/hg19/")

# ------- Initialize the Seurat object with the raw (non-normalized data) -------
pbmc3k <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)

pbmc3k[["percent.mt"]] <- PercentageFeatureSet(pbmc3k, pattern = "^MT-")
pbmc3k <- subset(pbmc3k, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

# ------- Subset the data -------
# pbmc3k_QA <- pbmc3k
pbmc3k_QA <- pbmc3k[,1:2048]

pbmc3k_QA <- SCTransform(pbmc3k_QA, method = "glmGamPoi", vars.to.regress = "percent.mt", verbose = FALSE)
pbmc3k_QA <- RunPCA(pbmc3k_QA, features = VariableFeatures(object = pbmc3k_QA))
```

## Neighbours evaluation, SNN
```{r}
n = ncol(pbmc3k_QA)
dim(pbmc3k_QA)

type = c("_", "_trimmed_", "_negedges_", "_trimmed_negedges_")
id_type = 2
dim = 15
k = 16
coff = 0 #0.067 #1/15
ord = 16

pbmc3k_QA <- FindNeighbors(pbmc3k_QA, reduction = "pca", dims = 1:dim, k.param=k, compute.SNN=TRUE, prune.SNN=coff)

pbmc3k_QA_snn_temp <- pbmc3k_QA@graphs[["SCT_snn"]]

dim(pbmc3k_QA_snn_temp)
pbmc3k_QA_snn <- pbmc3k_QA_snn_temp - diag(n)

# ------- limitation of nodes degrees SYMMETRIC -------
for (i in 1:n){
  to_delete <- order(pbmc3k_QA_snn[,i], decreasing = TRUE)[seq(ord+1,n,1)]
  pbmc3k_QA_snn[,i][to_delete] <- integer(n-ord)
  pbmc3k_QA_snn[i,][to_delete] <- integer(n-ord)
}
```

## Plot and save graphs 
```{r setup}
library(reticulate)
virtualenv_create("scrna_proj")
# py_install(c("networkx","matplotlib"), envname = "scrna_proj")
use_virtualenv("scrna_proj")
```

```{python}
import numpy as np
import networkx as nx
from matplotlib import pyplot as plt

id_type, type = int(r.id_type)-1, r.type
n = int(r.n)
k = int(r.k)
ord = int(r.ord)
dim = int(r.dim)

file_name = ''.join(["../../graphs/pbmc3k/", str(n), "_graph_snn", "_k", str(k), "_dim", str(dim), type[id_type], str(ord), ".gexf"])

G = nx.from_numpy_matrix(r.pbmc3k_QA_snn)
nx.write_gexf(G, file_name)

G = nx.read_gexf(file_name)
pos = nx.spring_layout(G)
plt.cla()
nx.draw_networkx_nodes(G, pos, node_size=10, nodelist=G.nodes)
nx.draw_networkx_edges(G, pos, edgelist=G.edges, style='solid', alpha=0.5, width=1)

file_name = ''.join(["../../graphs/pbmc3k/", str(n), "_graph_snn", "_k", str(k), "_dim", str(dim), type[id_type], str(ord), ".png"])
plt.savefig(file_name, bbox_inches='tight')
```
